theme: to minima
title: Destiny 
author: Yohana Habtu
email: yohana.habtug@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We are born into this world pure, like an empty vessel or a sponge that is willing to learn and absorb off the environment we are born in to. 
  Every choice is made for us that range from what we eat to how we dress on the outside. And this is further extended to controlling how we feel
  or how we should be feeling to certain things or events, yet we have never been asked how we felt about anything. I have learned of the years that
  the only person I could truly relay on was myself and that in times have failed me horribly and a times was the best choice to have had made. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  yoahanh-dev # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
